services:
  frontend:
    build:
      context: ./frontend-new
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    # environment:
      # Add your environment variables here
      # REACT_APP_API_URL: http://backend:5000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    # environment:
      # Add your environment variables here
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
